### PR TITLE
Professional_Portfolio

### PR DESCRIPTION
**Pull request by SphiweJoe**
Created a portfolio project with my professional summary

### CODE REVIEW

**Review by NuffSaid-Bore — CHANGES_REQUESTED** [review]
@SphiweJoe Nice work man. Provide Links to your socials when a user clicks on them to be redirected to the appropriate sites.
Screenshot 2024-11-19 153206

On Your footer when a user clicks your name it redirects to the colorlib website...consider changing the href 

Screenshot 2024-11-19 153701

**Review by TshepoMagagula — CHANGES_REQUESTED** [review]
Screenshot (51
@SphiweJoe Try to properly position your chatbot (preferably it should be rooted to the bottom right) to avoid it not being fully visible

**Review by TshepoMagagula — CHANGES_REQUESTED** [review]
Screenshot 52
@SphiweJoe try to have a consistent size for your project images, and maybe add a short description for each project

**Comment by Sinawo** [comment]
@SphiweJoe, this is fire🔥🔥🔥  Please just attend the reviews from @NuffSaid-Bore and @TshepoMagagula

**Review by zolwethu — CHANGES_REQUESTED** [review]
@SphiweJoe, this should be a given in all your projects. Make the chatbot style and feel somewhat similar to the rest of the pages, because now it kinda seems like it got the wrong dress code for the party... it stands out, looking like it doesnt belong

**Comment by SphiweJoe** [comment]
> @SphiweJoe, this should be a given in all your projects. Make the chatbot style and feel somewhat similar to the rest of the pages, because now it kinda seems like it got the wrong dress code for the party... it stands out, looking like it doesnt belong

@NuffSaid-Bore @TshepoMagagula @zolwethu I have made the requested changes please review them and give me permission to merge

**Review by TshepoMagagula — APPROVED** [review]
@SphiweJoe Good work!, the project looks perfect now, you can merge

**Review by NuffSaid-Bore — APPROVED** [review]
@SphiweJoe You're good to go.Go ahead and merge

**Pull request merged**
